### ISSUE TITLE
Release new version to operator HUB

### ISSUE THREAD

**Issue by mcerkez88** [Apicurio/apicurio-registry-operator#168]
Hi could you please share a roadmap when will new version of operator be published into operator hub?
Current version is 1.0.0-v2.0.0.final from May 2021.
If there are some prerequisites on release or there is a need to do some addition work feel to let me know if I can help speed up the release process.

**Comment by jmartin127** [comment]
I am also running into this issue.  I tried to add some annotations to my deployed pods today, only to find that this was [committed to master](https://github.com/Apicurio/apicurio-registry-operator/commit/09f653425d76c04cece2ab686c4c2b68d03f88a7) on Jan 31, 2022, but I am not yet able to use it via my OLM install because there has been no release pushed. 

Is there anything we can do from the community to help with this?

**Comment by uqix** [comment]
Any progress? the current used image is too old.

**Comment by EricWittmann** [comment]
We're actively working on this. And by this I mean a new release of apicurio registry.  Which will be a new product release for Red hat. And as a result useful updates to the operator and a new version in operator hub. Stay tuned over the next two weeks or so.
