### ISSUE TITLE
Prepare for breaking changes in K8s 1.25 / OCP 4.12

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry-operator#181]
See https://connect.redhat.com/en/blog/updating-your-operators-openshift-when-kubernetes-changes-apis .
In particular, `PodDisruptionBudget` is no longer `v1beta1`.

**Comment by martin-aders** [comment]
This ticket thankfully got solved recently but is not yet available as a stable release. OCP 4.12 is available now and I would prefer to upgrade the operator to a stable version rather than using the dev version which is also 2 years old. Are there plans to tag a new release?

Particularly, the current apicurio-registry-operator v1.0.0 has 3 issues that are partially fixed on the main branch that would be worth a release: 
* This issue #181 itself, for the breaking changes that prevent the ARO 4.12 upgrade
* Memory leak: The operator by default has 100MiB memory, and memory usage grows linearly over time with a rate of 200-400Mb/hour (with/without reduced log level), leading to an out-of-memory restart every 15-30 minutes.
* Endless reconciliation loop (causes unnecessary load on the API server and causes 300 logged messages/min or 76.23MB/day amount of logs), see also issue #93.
