### ISSUE TITLE
UI Behind NGINX on sub-path

### ISSUE THREAD

**Issue by mikementzmaersk** [Apicurio/apicurio-registry-operator#186]
Is there any advice or plans for placing the UI on a sub path for reverse proxies like NGINX?

eg /apicurioui

It seems most of the url's returned all use absolute rather than relative paths, which makes it tricky to obtain a stable UI experience without a lot of tweaks to our nginx proxy_pass.

Just wondering if there was anything in the base apicurio config? so we could update the CRD and operator so that it could be passed along.

**Comment by EricWittmann** [comment]
This has come up a few times in the past and I've never fully addressed it.  Well that ends today!  Or at least I hope so.

I've added a new option to tell the registry where the UI context really is, for cases where an external proxy or ingress is set up to relocate it.  The main problem is the root `index.html` file in the React UI.  It sets a base href in the HTML response.  In the past, we've just set the base href to `/ui/` because that's where the UI is located.  Well now it will be set to whatever you configure via `REGISTRY_UI_ROOT`.

See the attached PR.

As for the operator - the next version should make it easier to set custom environment variables like this new one.  @jsenko can provide more details.
